# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2edf64c429ebdb7bd7606a38e8df6c051859aa22894ebef37d865d79a3b29da6495acfd37d18db536103cbc4527e544cd2e2144d04fe0fcbdbf3ffbb98fb34

test:
  secret_key_base: 30ef1054e70214e55ca6335bbb97776ce471037267c0241b8e904647c8b15d383d98614335f55fe215baeedd7785038d95a5e199884405ff0ac37ec1e7783240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
